# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tales of Trinity
email: tales.of.trinity.lps@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hier findust du die LetÂ´ Plays die dir gefallen!!!
  Besuche uns doch auch auf Twitter und co. um Up to date zu sein.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tales-of-trinity.github.io" # the base hostname & protocol for your site
twitter_username: talesoftrinity
github_username:  tales-of-trinity

# Build settings
markdown: kramdown
